//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partikkels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVS_Table_final
    {
        public int Id { get; set; }
        public string MaalestedId { get; set; }
        public string Maalested { get; set; }
        public Nullable<System.DateTime> DatoMaerke { get; set; }
        public string StofId { get; set; }
        public string StofNavn { get; set; }
        public string EnhedId { get; set; }
        public string Enhed { get; set; }
        public Nullable<double> Resultat { get; set; }
        public string UdstyrId { get; set; }
        public string Navn { get; set; }
    }
}
