//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partikkels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resault_PM10
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DatoMaerke { get; set; }
        public string StofNavn { get; set; }
        public Nullable<double> Resultat { get; set; }
    }
}
